version: '3'
services:
  db:
    container_name: db
    image: postgres:12
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d
  # server:
  #   container_name: server
  #   build: ./server
  #   ports:
  #    - 8080:8080
  client:
    container_name: web
    build: ./web
    ports:
     - 3000:3000
