version: '3'
services:
  db:
    container_name: db
    image: postgres:12
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs
  server:
    container_name: server
    build: ./server
    ports:
     - 3000:3000
  client:
    container_name: web
    build: ./web
    ports:
     - 8080:3000
