version: '3'
services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    ports:
     - 3306:3306
    networks:
     - shared-network
    environment:
      MYSQL_ROOT_PASSWORD: EnglishAreSoAwesome!
      MYSQL_DATABASE: english_app
    volumes:
      - /opt/mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 2G
  server:
    container_name: server
    restart: always
    build: ./server
    ports:
     - 8080:8080
    depends_on:
     - mysql
    networks:
     - shared-network
    volumes:
      - .:/app
      - .:/app/node_modules/bcrypt/
    deploy:
      resources:
        limits:
          memory: 1G
  client:
    container_name: web
    restart: always
    build: ./web
    ports:
     - 80:80
    networks:
     - shared-network
    deploy:
      resources:
        limits:
          memory: 1G

networks:
  shared-network:
