version: '3'
services:
  db:
    container_name: db
    image: postgres:11.13
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - transcendence
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    command: postgres -c stats_temp_directory=/tmp
  server:
    container_name: server
    build: ./server
    environment:
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - SERVER_HOST=${SERVER_HOST}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      englishapp:
        ipv4_address: 172.20.0.5
    depends_on:
      - db
  client:
    container_name: web
    build: ./web
    ports:
      - 3000:3000
    networks:
      - englishapp
networks:
  englishapp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
